version: '3.7'

services:
  nginx:
    image: nginx:alpine
    container_name: market-balancer
    volumes:
      - ./public:/srv/app/public:cached
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

    ports:
      - ${HTTP_LOCAL_PORT:-80}:80

    depends_on:
      - php

  php:
    image: mexoboy/laravel:latest
    container_name: market
    working_dir: /srv/app
    volumes:
      - ./:/srv/app

    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: market-db

    environment:
      POSTGRES_DB: ${DB_DATABASE:-market}
      POSTGRES_USER: ${DB_USERNAME:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-12345}
      PGDATA: /data

    ports:
      - 127.0.0.1:${LOCAL_DB_PORT:-5432}:5432

    volumes:
      - dbdata:/data

volumes:
  dbdata:
